version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # persist DB data
      - ./db/init:/docker-entrypoint-initdb.d # run SQL scripts on first startup
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
      timeout: 5s

  backend:
    build:
      context: ./api
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      OPENAI_KEY: ${OPENAI_KEY}
      YOUTUBE_KEY: ${YOUTUBE_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  ui:
    build:
      context: ./ui
    container_name: nextjs-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
